version: '3.4'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - '5431:5431'
    expose:
      - '5431'
    networks:
    - lolipad2

  logistic:
    build: 
      context: .
    depends_on:
      - postgres
    environment: 
      APP_NAME: logistic_service
      VERSION: 1.0.0
      PORT: 3030
      HOST: 0.0.0.0
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      DB_HOSTNAME: postgres
      DB_PORT: 543
      DB_NAME: logistic_service
      DB_DIALECT: postgres
      HOST_ORIGIN: localhost
      API_AUTH_URL: http://localhost:3000
    ports:
      - '3030:3030'
    expose:
      - '3030'
    networks:
    - lolipad2
    

networks:
  lolipad2:
    driver: bridge